# THIS SIMPLE SCRIPT CLEANS THE BEHAVIOUR STATISTIS BY ARENA GENERATED BY ETHOANALYSIS
# FROM COLUMNS WITH MISSING DATA. OUTPUTS IN PROCESSED DATA, AVAILABLE IN GITHUB.

# Assuming working directory in file source location.
setwd('../..')
features <- read.csv("data/raw/raw_data/Handcrafted_features/BehaviourStatisticsByArena.csv")

features <- features[, c(apply(features, 2, function(x) !any(is.na(x))))]

features <- features[complete.cases(features), ]

write.csv(features[, c(3, 7:33)], 'data/processed/Hidden_representations/Hand_features/handcrafted_dimensions.csv', row.names = FALSE)
write.csv(features[, c(1:6)], 'data/processed/Hidden_representations/Hand_features/handcrafted_dimensions_meta_info.csv', row.names = FALSE)


